### ISSUE TITLE
Make it compatible with current TYPO3 versions

### ISSUE THREAD

**Issue by simonschaufi** [heiko-hardt/behat-typo3-extension#1]
As this extension is outdated, it would be great to update it to make it work with current TYPO3 and behat versions (v3.5.0). I'm even willing to sponsor the development. My requirement is that it also works with "helhum/dotenv-connector" instead of writing the DB config into LocalConfiguration.php

**Comment by heiko-hardt** [comment]
Hi Simon, thank's you for your interest :)
I will have a look at it this weekend. I promise.
There is no need for a donation. Mabe you can help me supporting this extension.

Kind regards
Heiko

**Comment by simonschaufi** [comment]
I try my best but I find it really difficult to understand the symfony parts (service container and so on).

**Comment by heiko-hardt** [comment]
Hi Simon, the symfony part isn't the problem.
A test-/bootstrap class has been moved to a seperate bundle. This needs to be adapted.
I guess it took 2-3 weekends. I will keep you up to date. ok?

**Comment by simonschaufi** [comment]
Ok ;) Hope to see a first draft version soon.

This is my source of inspiration except that laravel has .env support out of the box while we need to include that somehow. See https://github.com/laracasts/Behat-Laravel-Extension

**Comment by heiko-hardt** [comment]
Thank's for the link. I think the .env support shouldn't be hard.
First draft looks promising, but i'm verry unhappy about the architecture and implementation.
I have registered a new repository for handling the TYPO3 bootstrap like "typo3\test-framework".
This should support TYPO3 from version 6.2.x to the current master.

**Comment by simonschaufi** [comment]
I have switched to codeception now which is better than behat.
